import pygame
pygame.mixer.init()
music1 = pygame.mixer.Sound('main/3_functions/hangman_sounds/background.mp3')
music2 = pygame.mixer.Sound('main/3_functions/hangman_sounds/winner.mp3')
# pygame.mixer.music.load("main/3_functions/hangman_sounds/background.mp3") 
# pygame.mixer.music.set_volume(0.7) 
# pygame.mixer.music.play()
# pygame.input()
# pygame.mixer.music.load("main/3_functions/hangman_sounds/winner.mp3") 
# pygame.mixer.music.play()
input()
pygame.mixer.Channel(0).set_volume(0.1)
pygame.mixer.Channel(0).play(music1)
input()
pygame.mixer.Channel(1).play(music2)
input()
pygame.mixer.Channel(0).set_volume(0.5)
pygame.mixer.Channel(0).play(music1)
input()
